### ISSUE TITLE
l2mapconv latest public version

### ISSUE THREAD

**Issue by RostMyr** [madyanov/cgen#1]
Hi @madyanov 

I apologize for reaching out through a github issue, but the platform doesn't support private messages. I'm in search of the latest public version of l2mapconv. It appears you might have been the primary contributor. I've found a dozen forks at various stages of development, but finding the most recent version has been challenging. I'm beginning to wonder if it has been made private.

Could you please help me find the latest public version, or tell me where to look?

Thanks,
Rost

**Comment by madyanov** [comment]
Sure, I think this in the one: [l2mapconv-public.zip](https://github.com/madyanov/cgen/files/14398099/l2mapconv-public.zip)
It's a git repository, so you can `git branch`.

Also, don't use it to generate geodata :)
It uses voxelization and some heuristic rules, but there's better approach with actual capsule-to-triangle collision detection that is not implemented.

**Comment by RostMyr** [comment]
Hey,
Thanks for the quick reply and for sharing the sources!

> Also, don't use it to generate geodata :)
It uses voxelization and some heuristic rules, but there's better approach with actual capsule-to-triangle collision detection that is not implemented.

Noted! :)

Best,
Rost
